name: auto_pr

on:
  push:
    branches:
      - trunk

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: gh pr create --base main --title $(git log -1 --pretty=format:'%s') --body $(git log -1 --pretty=format:'%s')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
