name: auto_publish

on:
  pull_request:
    branches: [ main ]
    types:
      - closed

jobs:
  build_publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: git config --global pull.ff only
      - run: git config --global user.email "autotag@ksyun.com"
      - run: git config --global user.name "autotag"
      - run: git pull
      - run: npm i
      - run: npm run test
      - run: npm run build
      - run: git add . && git commit -m 'auto_publish'
      - run: npm version patch
      - run: gh release create $(git describe --tags `git rev-list --tags --max-count=1`) --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
